openapi: "3.0.0"
info:
  title: "Wutsi Stats API"
  description: |
    API for querying Statistics
  version: "1.0.0"

servers:
  - url: https://wutsi-stats-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-stats-prod.herokuapp.com
    description: Production

paths:
  /v1/views:
    get:
      operationId: "search"
      summary: "Search views"
      parameters:
        - in: query
          name: story-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: user-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: device-id
          schema:
            type: string
            format: uuid
            nullable: true
        - in: query
          name: start-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: end-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchViewResponse'
      tags:
        - Stats
  /v1/replay:
    get:
      operationId: "replay"
      summary: "Rebuild statistics"
      description: |
        This process will rebuild the stats by reprocessing all the user interaction messages from S3 for the provided start/end date.
      parameters:
        - in: query
          name: start-date
          schema:
            type: string
            format: date
            required: true
        - in: query
          name: end-date
          schema:
            type: string
            format: date
            nullable: true
      responses:
        200:
          description: Success

components:
  schemas:
    SearchViewResponse:
      type: object
      properties:
        views:
          type: array
          items:
            $ref: "#/components/schemas/View"

    View:
      type: object
      properties:
        id:
          type: integer
          format: int64
        storyId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
          nullable: true
        deviceId:
          type: string
          format: uuid
        hitId:
          type: string
          format: uuid
        source:
          type: string
          nullable: true
        medium:
          type: string
          nullable: true
        campaign:
          type: string
          nullable: true
        referer:
          type: string
          nullable: true
        viewDateTime:
          type: string
          format: date-time
