openapi: "3.0.0"
info:
  title: "Wutsi Stats API"
  description: |
    API for querying Statistics
  version: "1.0.0"

servers:
  - url: https://wutsi-stats-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-stats-prod.herokuapp.com
    description: Production

paths:
  /v1/views:
    get:
      operationId: "views"
      summary: "Search views"
      parameters:
        - in: query
          name: story-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: user-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: device-id
          schema:
            type: string
            format: uuid
            nullable: true
        - in: query
          name: start-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: end-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchViewResponse'
      tags:
        - Views

  /v1/replay/daily:
    get:
      operationId: "replayDaily"
      summary: "Rebuild daily statistics"
      description: |
        This process will rebuild the daily statistic by reprocessing all the user interaction messages from S3 for the provided start/end date.
      parameters:
        - in: query
          name: start-date
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: end-date
          required: true
          schema:
            type: string
            format: date
            nullable: true
      responses:
        200:
          description: Success
      tags:
        - Views

  /v1/replay/monthly:
    get:
      operationId: "replayMonthly"
      summary: "Rebuild monthly statistics"
      description: |
        This process will rebuild the monthly statistic.
        The montly statistics are aggregated from the daily statistics
      parameters:
        - in: query
          name: start-date
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: end-date
          required: true
          schema:
            type: string
            format: date
            nullable: true
      responses:
        200:
          description: Success
      tags:
        - Views


  /v1/kpis/stories/daily:
    get:
      operationId: "storyDailyKpis"
      summary: "Story Daily KPIs"
      parameters:
        - in: query
          name: story-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: user-id
          description: ID of the author of the Story
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: type
          schema:
            type: string
            nullable: true
        - in: query
          name: start-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: end-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchStoryKpiResponse'
      tags:
        - KPI

  /v1/kpis/stories/monthly:
    get:
      operationId: "storyMonthlyKpis"
      summary: "Story Monthly KPIs"
      parameters:
        - in: query
          name: story-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: user-id
          description: ID of the author of the Story
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: type
          schema:
            type: string
            nullable: true
        - in: query
          name: year
          schema:
            type: integer
            format: in32
        - in: query
          name: month
          schema:
            type: integer
            format: in32
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchStoryKpiResponse'
      tags:
        - KPI

  /v1/kpis/users/{user-id}/monthly:
    get:
      operationId: "userMonthlyKpis"
      summary: "User Monthly KPIs"
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: type
          schema:
            type: string
        - in: query
          name: year
          schema:
            type: integer
            format: in32
        - in: query
          name: month
          schema:
            type: integer
            format: in32
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUserKpiResponse'
      tags:
        - KPI


  /v1/traffics/users/{user-id}/monthly:
    get:
      operationId: "userMonthlyTraffic"
      summary: "User Monthly Traffic"
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: year
          schema:
            type: integer
            format: in32
        - in: query
          name: month
          schema:
            type: integer
            format: in32
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUserTrafficResponse'
      tags:
        - Traffic

  /v1/traffics/stories/{story-id}/monthly:
    get:
      operationId: "storyMonthlyTraffic"
      summary: "Story Monthly Traffic"
      parameters:
        - in: path
          name: story-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: year
          schema:
            type: integer
            format: in32
        - in: query
          name: month
          schema:
            type: integer
            format: in32
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchStoryTrafficResponse'
      tags:
        - Traffic


  /v1/stories/import:
    get:
      operationId: "importStories"
      summary: "Import stories"
      responses:
        200:
          description: Success
      tags:
        - Migration

components:
  schemas:
    SearchViewResponse:
      type: object
      properties:
        views:
          type: array
          items:
            $ref: "#/components/schemas/View"

    View:
      type: object
      properties:
        id:
          type: integer
          format: int64
        storyId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
          nullable: true
        deviceId:
          type: string
          format: uuid
          nullable: true
        hitId:
          type: string
          format: uuid
        source:
          type: string
          nullable: true
        medium:
          type: string
          nullable: true
        campaign:
          type: string
          nullable: true
        referer:
          type: string
          nullable: true
        viewDateTime:
          type: string
          format: date-time
        traffic:
          type: string
          nullable: true


    SearchStoryKpiResponse:
      type: object
      properties:
        kpis:
          type: array
          items:
            $ref: "#/components/schemas/StoryKpi"

    StoryKpi:
      type: object
      properties:
        id:
          type: integer
          format: int64
        storyId:
          type: integer
          format: int64
        type:
          type: string
        date:
          type: string
          format: date
        value:
          type: integer
          format: int64


    SearchUserKpiResponse:
      type: object
      properties:
        kpis:
          type: array
          items:
            $ref: "#/components/schemas/UserKpi"

    UserKpi:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        type:
          type: string
        date:
          type: string
          format: date
        value:
          type: integer
          format: int64


    SearchUserTrafficResponse:
      type: object
      properties:
        traffics:
          type: array
          items:
            $ref: "#/components/schemas/UserTraffic"

    UserTraffic:
      type: object
      properties:
        name:
          type: string
          nullable: true
        userId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        value:
          type: integer
          format: int64


    SearchStoryTrafficResponse:
      type: object
      properties:
        traffics:
          type: array
          items:
            $ref: "#/components/schemas/StoryTraffic"

    StoryTraffic:
      type: object
      properties:
        name:
          type: string
          nullable: true
        storyId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        value:
          type: integer
          format: int64
