openapi: "3.0.0"
info:
  title: "Wutsi Stats API"
  description: |
    API for managing the platform Key Performance Metrics
  version: "1.0.0"

servers:
  - url: https://wutsi-stats-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-stats-prod.herokuapp.com
    description: Production

paths:
  /v1/views:
    get:
      operationId: "views"
      summary: "Search views"
      parameters:
        - in: query
          name: story-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: user-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: device-id
          schema:
            type: string
            format: uuid
            nullable: true
        - in: query
          name: start-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: end-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchViewResponse'
      security:
        - api_key: [ 'stats-read' ]
      tags:
        - Views

  /v1/replay/daily:
    get:
      operationId: "replay-daily"
      summary: "Rebuild daily statistics"
      description: |
        This process will rebuild the daily statistic by reprocessing all the user interaction messages from S3 for the provided start/end date.
      parameters:
        - in: query
          name: start-date
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: end-date
          required: true
          schema:
            type: string
            format: date
            nullable: true
      responses:
        200:
          description: Success
      security:
        - api_key: [ 'stats-manage' ]
      tags:
        - Views

  /v1/replay/monthly:
    get:
      operationId: "replay-monthly"
      summary: "Rebuild monthly statistics"
      description: |
        This process will rebuild the monthly statistic.
        The montly statistics are aggregated from the daily statistics
      parameters:
        - in: query
          name: start-date
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: end-date
          required: true
          schema:
            type: string
            format: date
            nullable: true
      responses:
        200:
          description: Success
      security:
        - api_key: [ 'stats-manage' ]
      tags:
        - Views


  /v1/kpis/stories/daily:
    get:
      operationId: "story-daily-kpis"
      summary: "Story Daily KPIs"
      parameters:
        - in: query
          name: story-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: user-id
          description: ID of the author of the Story
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: type
          schema:
            type: string
            nullable: true
        - in: query
          name: start-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: end-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchStoryKpiResponse'
      security:
        - api_key: [ 'stats-read' ]
      tags:
        - KPI

  /v1/kpis/stories/monthly:
    get:
      operationId: "story-monthly-kpis"
      summary: "Story Monthly KPIs"
      parameters:
        - in: query
          name: story-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: user-id
          description: ID of the author of the Story
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: type
          schema:
            type: string
            nullable: true
        - in: query
          name: year
          schema:
            type: integer
            format: in32
        - in: query
          name: month
          schema:
            type: integer
            format: in32
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchStoryKpiResponse'
      security:
        - api_key: [ 'stats-read' ]
      tags:
        - KPI

  /v1/kpis/users/{user-id}/monthly:
    get:
      operationId: "user-monthly-kpis"
      summary: "User Monthly KPIs"
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: type
          schema:
            type: string
        - in: query
          name: year
          schema:
            type: integer
            format: in32
        - in: query
          name: month
          schema:
            type: integer
            format: in32
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUserKpiResponse'
      security:
        - api_key: [ 'stats-read' ]
      tags:
        - KPI

  /v1/kpis/users/{user-id}/monthly/email:
    get:
      operationId: "email-user-monthly-kpis"
      summary: "Send via email Monthly KPIs to a user"
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: date
          required: true
          description: |
            Date for which we want to generate the email.
            If date is `2020-10-01`, the email will be generated for the month of October 2020
          schema:
            type: string
            format: date
      responses:
        200:
          description: Success
      security:
        - api_key: [ 'stats-manage' ]
      tags:
        - KPI

  /v1/kpis/users/monthly/email:
    get:
      operationId: "email-monthly-kpis"
      summary: "Send via email Monthly KPIs to all user"
      parameters:
        - in: query
          name: date
          required: true
          description: |
            Date for which we want to generate the email.
            If date is `2020-10-01`, the email will be generated for the month of October 2020
          schema:
            type: string
            format: date
      responses:
        200:
          description: Success
      security:
        - api_key: [ 'stats-manage' ]
      tags:
        - KPI



  /v1/traffics/users/{user-id}/monthly:
    get:
      operationId: "user-monthly-traffic"
      summary: "User Monthly Traffic"
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: year
          schema:
            type: integer
            format: in32
        - in: query
          name: month
          schema:
            type: integer
            format: in32
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUserTrafficResponse'
      security:
        - api_key: [ 'stats-read' ]
      tags:
        - Traffic

  /v1/traffics/stories/{story-id}/monthly:
    get:
      operationId: "story-monthly-traffic"
      summary: "Story Monthly Traffic"
      parameters:
        - in: path
          name: story-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: year
          schema:
            type: integer
            format: in32
        - in: query
          name: month
          schema:
            type: integer
            format: in32
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchStoryTrafficResponse'
      security:
        - api_key: [ 'stats-read' ]
      tags:
        - Traffic


  /v1/stories/import:
    get:
      operationId: "import-stories"
      summary: "Import stories"
      responses:
        200:
          description: Success
      security:
        - api_key: [ 'stats-manage' ]
      tags:
        - Migration

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    SearchViewResponse:
      type: object
      properties:
        views:
          type: array
          items:
            $ref: "#/components/schemas/View"

    View:
      type: object
      properties:
        id:
          type: integer
          format: int64
        storyId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
          nullable: true
        deviceId:
          type: string
          format: uuid
          nullable: true
        hitId:
          type: string
          format: uuid
        source:
          type: string
          nullable: true
        medium:
          type: string
          nullable: true
        campaign:
          type: string
          nullable: true
        referer:
          type: string
          nullable: true
        viewDateTime:
          type: string
          format: date-time
        traffic:
          type: string
          nullable: true
        readTimeSeconds:
          type: integer


    SearchStoryKpiResponse:
      type: object
      properties:
        kpis:
          type: array
          items:
            $ref: "#/components/schemas/StoryKpi"

    StoryKpi:
      type: object
      properties:
        id:
          type: integer
          format: int64
        storyId:
          type: integer
          format: int64
        type:
          type: string
        date:
          type: string
          format: date
        value:
          type: integer
          format: int64


    SearchUserKpiResponse:
      type: object
      properties:
        kpis:
          type: array
          items:
            $ref: "#/components/schemas/UserKpi"

    UserKpi:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        type:
          type: string
        date:
          type: string
          format: date
        value:
          type: integer
          format: int64


    SearchUserTrafficResponse:
      type: object
      properties:
        traffics:
          type: array
          items:
            $ref: "#/components/schemas/UserTraffic"

    UserTraffic:
      type: object
      properties:
        name:
          type: string
          nullable: true
        userId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        value:
          type: integer
          format: int64


    SearchStoryTrafficResponse:
      type: object
      properties:
        traffics:
          type: array
          items:
            $ref: "#/components/schemas/StoryTraffic"

    StoryTraffic:
      type: object
      properties:
        name:
          type: string
          nullable: true
        storyId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        value:
          type: integer
          format: int64
