@startuml
Actor reader


node "Like Capability" {
 () REST
 () Events

 node "Web App" {
  [Like Widget]
  reader --> [Like Widget]
 }

 
 node "Like Service" {
  [Like Widget] -> REST
  REST -- [Like API]
  [Like API] - Events

  database "DB"{
   [LikeDB]
   [Like API] --> [LikeDB]
  }

  database "Cache"{
   [LikeCache]
   [Like API] --> [LikeCache]
  }
 }

}

Events --> [3rd Party Service]
[3rd Party App] --> REST
@enduml
