@startuml
Actor reader
() REST
() Events


node "Web App" {
  [Like Widget]
  reader --> [Like Widget]
}

node "Mobile App" {
  [Like Mobile Widget]
  reader --> [Like Mobile Widget]
}



node "Wutsi" {
 [Like Widget] --> REST
 [Like Mobile Widget] --> REST
 REST - [Like API]
 [Like API] - Events

 database "DB"{
   [LikeDB]
   [Like API] --> [LikeDB]
 }

 database "Cache"{
   [LikeCache]
   [Like API] --> [LikeCache]
 }
}

node "3rd Party" {
  [3rd Party Service]
  [3rd Party Service] -> Events
}
@enduml
