@startuml
class Author {
  fullName
  email
}

class Blog {
  name
}


class Story {
}

class StoryContent {
  language
  content
}

Author -> Blog
Blog -> "*" Story
Story -> "*" StoryContent
@enduml
