@startuml
class Author {
  fullName
  email
}

class Blog {
  name
}

class Site {
}

class Story {
}


class Channel {
  name
}


Author -> Blog
Blog -> "*" Channel
Blog "*" --> Site
Blog -> "*" Story
Story -> Channel: is-published-to
@enduml
