openapi: "3.0.0"
info:
  title: "Wutsi Contract API"
  description: |
    API for managing blogger contracts
  version: "1.0.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/contracts/active:
    get:
      operationId: "active"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchContractResponse'
      tags:
        - Contract

components:
  schemas:
    SearchContractResponse:
      type: object
      properties:
        contracts:
          type: array
          items:
            $ref: "#/components/schemas/Contract"

    Contract:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        startDate:
          type: integer
          format: int64
          nullable: true
        endDate:
          type: integer
          format: int64
          nullable: true
        amount:
          type: number
          format: int64
        currency:
          type: string
