openapi: "3.0.0"
info:
  title: "Wutsi User API"
  description: |
    This API manages the Users.
  version: "1.0.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/users/{id}:
    get:
      operationId: "get"
      summary: "Return the information of a user"
      parameters:
        - in: path
          name: id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
      tags:
        - User

  /v1/users/{id}/followers:
    get:
      operationId: "get"
      summary: "Return followers of a given user"
      parameters:
        - in: path
          name: id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchFollowerResponse'
      tags:
        - Follower

components:
  schemas:
    GetUserResponse:
      type: object
      properties:
        user:
          type: object
          $ref: "#/components/schemas/User"

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        name:
          type: string
        email:
          type: string
          nullable: true
        fullName:
          type: string
        pictureUrl:
          type: string
          format: uri
        language:
          type: string

    SearchFollowerResponse:
      type: object
      properties:
        user:
          type: object
          $ref: "#/components/schemas/Follower"

    Follower:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        followerUserId:
          type: integer
          format: int64
