openapi: "3.0.0"
info:
  title: "Wutsi Recommendation API"
  description: |
    Recommendation API
  version: "1.0.0"

servers:
  - url: https://wutsi-recommend-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-recommend-prod.herokuapp.com
    description: Production

paths:
  /v1/recommendations/feeds/stories:
    get:
      operationId: "create-story-feed"
      summary: Create the Story CSV
      description: |
        Create the Story CSV feed, that will be used for training the AI model.
      parameters:
        - in: query
          name: site-id
          description: ID of the Site
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: version
          description: Version of the feed schemas
          schema:
            type: integer
            format: int64
            nullable: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFeedResponse'
      security:
        - api_key: [ 'recommend-manage' ]
      tags:
        - Feeds

  /v1/recommendations/feeds/interactions:
    get:
      operationId: "create-interaction-feed"
      summary: Create teh user interaction feed
      description: |
        Create the Story CSV feed, that will be used for training the AI model.
      parameters:
        - in: query
          name: site-id
          description: ID of the Site
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: version
          description: Version of the feed schemas
          schema:
            type: integer
            format: int64
            nullable: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFeedResponse'
      security:
        - api_key: [ 'recommend-manage' ]
      tags:
        - Feeds


  /v1/recommendations/sync:
    get:
      operationId: "sync"
      summary: Syncronize the recommendation engine with latest data
      description: |
        Syncronize the recommendation engine with latest data
      parameters:
        - in: query
          name: site-id
          description: ID of the Site
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
      security:
        - api_key: [ 'recommend-manage' ]
      tags:
        - Sync

  /v1/recommendations/suggest:
    post:
      operationId: "suggest"
      summary: "Suggest stories"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuggestStoriesRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuggestStoriesResponse'
      security:
        - api_key: [ 'recommend-read' ]
      tags:
        - Recommendation

  /v1/recommendations/rank:
    post:
      operationId: "rank"
      summary: "Rank stories"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RankStoriesRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RankStoriesResponse'
      security:
        - api_key: [ 'recommend-read' ]
      tags:
        - Recommendation



components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    SuggestStoriesRequest:
      type: object
      properties:
        userId:
          type: string
          nullable: true
        storyId:
          type: string
          nullable: true
        deviceId:
          type: string
          nullable: true
        traffic:
          type: string
          nullable: true
        deviceType:
          type: string
          nullable: true
        language:
          type: string
          nullable: true
        limit:
          type: integer
          default: 20

    SuggestStoriesResponse:
      type: object
      properties:
        storyIds:
          type: array
          items:
            type: string


    RankStoriesRequest:
      type: object
      properties:
        userId:
          type: string
          nullable: true
        deviceId:
          type: string
          nullable: true
        storyIds:
          type: array
          items:
            type: string
        traffic:
          type: string
          nullable: true
        deviceType:
          type: string
          nullable: true
        language:
          type: string
          nullable: true

    RankStoriesResponse:
      type: object
      properties:
        storyIds:
          type: array
          items:
            type: string


    CreateFeedResponse:
      type: object
      properties:
        feedUrl:
          description: URL of the CSV file generated
          type: string
