openapi: "3.0.0"
info:
  title: "Wutsi Recommendation API"
  description: |
    Recommendation API
  version: "1.0.0"

servers:
  - url: https://wutsi-recommendation-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-recommendation-prod.herokuapp.com
    description: Production

paths:
  /v1/recommendations/feeds/stories:
    get:
      operationId: "create-story-feed"
      summary: Create the Story CSV
      description: |
        Create the Story CSV feed, that will be used for training the AI model
        The format of the CSV file:
        - story_id: ID of the product
        - categories: Topic, Sub-Topic, and tags. All separated by `|`
        - language: Story language
        - timestamp: Published date/time as epoc time.
      parameters:
        - in: query
          name: site-id
          description: ID of the Site
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFeedResponse'
      security:
        - api_key: [ 'recommend-manage' ]
      tags:
        - Feeds

  /v1/recommendations/feeds/interactions:
    get:
      operationId: "create-interaction-feed"
      summary: Create teh user interaction feed
      description: |
        Create the Story CSV feed, that will be used for training the AI model
        The format of the CSV file:
        - story_id: ID of the product
        - user_id: ID of the user
        - event_type: Type of event
        - event_value: Value of the event
        - device: Type of device: desktop, mobile, tablet
        - medium: Type of medium: mail, web
        - timestamp: interaction timestamp
      parameters:
        - in: query
          name: site-id
          description: ID of the Site
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFeedResponse'
      security:
        - api_key: [ 'recommend-manage' ]
      tags:
        - Feeds

  /v1/recommendations/similar:
    get:
      operationId: "get-similar"
      summary: "Return similar products"
      parameters:
        - in: query
          name: product-id
          description: ID of the Product for which we want to find similar products
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: user-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFeedResponse'
      security:
        - api_key: [ 'recommend-read' ]
      tags:
        - Recommendation


components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    GetSimilarProductsResponse:
      type: object
      properties:
        productIds:
          description: ID of the similar products, sorted from most similar to least similar
          type: array
          items:
            type: integer
            format: int64

    CreateFeedResponse:
      type: object
      properties:
        feedUrl:
          description: URL of the CSV file generated
          type: string
