openapi: "3.0.0"
info:
  title: "Wutsi Story API"
  description: |
    This API manages the Stories.
    The API offer the following functionalites:
    - Create Stories
    - Publish Stories
    - Return the content of Stories in various languages
  version: "1.0.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/story/{id}:
    get:
      operationId: "get"
      summary: "Return the information of a story"
      parameters:
        - in: path
          name: id
          description: ID of the site
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStoryResponse'
      tags:
        - Story

  /v1/stories/published:
    get:
      operationId: "published"
      summary: "Return the published stories"
      parameters:
        - in: query
          name: site-id
          schema:
            type: number
            format: int64
            default: 1
        - in: query
          name: start-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: end-date
          schema:
            type: string
            format: date
            nullable: true
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            format: int32
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchStoryResponse'
      tags:
        - Story

components:
  schemas:
    GetStoryResponse:
      type: object
      properties:
        story:
          type: object
          $ref: "#/components/schemas/Story"

    Story:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        siteId:
          type: integer
          format: int64
          example: 1
          default: 1
        userId:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "This is the story of my life"
          description: "Description of the Story"
        tagLine:
          type: string
          example: "It's all about the journey, not the destination"
        summary:
          type: string
          description: "Summary of the Story"
        slug:
          type: string
          format: url
          example: "https://www.wutsi.com/read/123/this-is-the-story-of-my-life"
        socialMediaMessage:
          type: string
          format: url
          nullable: true
          description: "Message to publish on social media. If not provided, the site of the story will be published"
        wppStatus:
          type: string
          nullable: true
        content:
          type: string
          description: "Content of the Story in the format of editorjs"
        readingMinutes:
          type: integer
          description: "Estimation of the reading time in minute"
        publishedDateTime:
          type: integer
          format: int64
        access:
          type: string
          description: |
            Access required to read the story. Possible values
            - `PUBLIC`: Accessible by everyone
            - `SUBSCRIBER`: Accessible only the blog subscriber
            - `PREMIUM_SUBSCRIBER`: Accessible only on subscriber who paid their subscription


    SearchStoryResponse:
      type: object
      properties:
        stories:
          type: array
          items:
            $ref: "#/components/schemas/StorySummary"

    StorySummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        siteId:
          type: integer
          format: int64
          example: 1
          default: 1
        userId:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "This is the story of my life"
          description: "Description of the Story"
        tagLine:
          type: string
          example: "It's all about the journey, not the destination"
        summary:
          type: string
          description: "Summary of the Story"
        slug:
          type: string
          format: url
          example: "https://www.wutsi.com/read/123/this-is-the-story-of-my-life"
        wppStatus:
          type: string
          nullable: true
        readingMinutes:
          type: integer
          description: "Estimation of the reading time in minute"
        publishedDateTime:
          type: integer
          format: int64
        access:
          type: string
          description: |
            Access required to read the story. Possible values
            - `PUBLIC`: Accessible by everyone
            - `SUBSCRIBER`: Accessible only the blog subscriber
            - `PREMIUM_SUBSCRIBER`: Accessible only on subscriber who paid their subscription
