openapi: "3.0.0"
info:
  title: "Wutsi Story API"
  description: |
    This API manages the Stories.
    The API offer the following functionalites:
    - Create Stories
    - Publish Stories
    - Return the content of Stories in various languages
  version: "0.0.1"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox

paths:
  /v1/story/{id}:
    get:
      operationId: "get"
      summary: "Return the information of a story"
      parameters:
        - in: path
          name: id
          description: ID of the site
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStoryResponse'
      tags:
        - Story

components:
  schemas:
    GetStoryResponse:
      type: object
      properties:
        site:
          type: object
          $ref: "#/components/schemas/Story"

    Story:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        siteId:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "This is the story of my life"
        tagName:
          type: string
          example: "It's all about the journey, not the destination"
        summary:
          type: string
        slug:
          type: string
          format: url
          example: "https://www.wutsi.com/read/123"
