openapi: "3.0.0"
info:
  title: "Wutsi Partner API"
  description: |
    Partner are parties having a business relationship with Wutsi:
    - A partner is paid based on the monthly read ratio of their stories
    - A partner can set payment plans to get paid subscribers on his blog
  version: "1.0.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/partners/active:
    get:
      operationId: "active"
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchPartnerResponse'
      tags:
        - Partner

components:
  schemas:
    SearchPartnerResponse:
      type: object
      properties:
        partners:
          type: array
          items:
            $ref: "#/components/schemas/Partner"

    Partner:
      type: object
      properties:
        id:
          type: integer
          format: int64
        siteId:
          type: integer
          format: int64
          default: 1
        userId:
          type: integer
          format: int64
        fullName:
          type: string
        email:
          type: string
          format: email
        mobileNumber:
          type: string
        mobileProvider:
          type: string
        countryCode:
          type: string
