openapi: "3.0.0"
info:
  title: "Wutsi Subscription API"
  description: |
    This API manages paid subscriptions
  version: "1.0.0"

servers:
  - url: https://wutsi-subscription-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-subscription-prod.herokuapp.com
    description: Production

paths:
  /v1/plans:
    post:
      operationId: "create-plan"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePlanRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatePlanResponse"
      security:
        - api_key: [ 'subscription' ]
      tags:
        - Plan

  /v1/plans/{plan-id}:
    post:
      operationId: "update-plan"
      parameters:
        - in: path
          name: plan-id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlanRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdatePlanResponse"
      security:
        - api_key: [ 'subscription' ]
      tags:
        - Plan

    get:
      operationId: "get-plan"
      parameters:
        - in: path
          name: plan-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: currency
          schema:
            type: string
            nullable: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPlanResponse"
      security:
        - api_key: [ 'subscription' ]
      tags:
        - Plan


  /v1/subscriptions:
    post:
      operationId: "create-subscription"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscriptionRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateSubscriptionResponse"
      security:
        - api_key: [ 'subscription' ]
      tags:
        - Subscription

  /v1/subscriptions/{subscription-id}:
    get:
      operationId: "get-subscription"
      parameters:
        - in: path
          name: subscription-id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSubscriptionResponse"
      security:
        - api_key: [ 'subscription' ]
      tags:
        - Subscription


  /v1/partners/{partner-id}/plans:
    get:
      operationId: "partner-plans"
      parameters:
        - in: path
          name: partner-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: currency
          schema:
            type: string
            nullable: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchPlanResponse'
      security:
        - api_key: [ 'subscription' ]
      tags:
        - Partner

  /v1/partners/{partner-id}/subscriptions:
    get:
      operationId: "partner-subscriptions"
      parameters:
        - in: path
          name: partner-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: status
          required: true
          schema:
            type: string
        - in: query
          name: subscriber-id
          required: false
          schema:
            type: number
            format: int64
            nullable: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchSubscriptionResponse"
      security:
        - api_key: [ 'subscription' ]
      tags:
        - Partner

  /v1/partners/{partner-id}/subscriptions/count:
    get:
      operationId: "partner-subscriptions-count"
      parameters:
        - in: path
          name: partner-id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: status
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CountSubscriptionResponse"
      security:
        - api_key: [ 'subscription' ]
      tags:
        - Partner


components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreatePlanRequest:
      type: object
      properties:
        siteId:
          type: integer
          format: int64
          nullable: true
        partnerId:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
        description:
          type: string
        monthlyRate:
          type: integer
          format: int64
        yearlyRate:
          type: integer
          format: int64
          minimum: 1
        currency:
          type: string
      required:
        - partnerId
        - siteId
        - name

    CreatePlanResponse:
      type: object
      properties:
        planId:
          type: integer
          format: int64


    UpdatePlanRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        active:
          type: boolean
        monthlyRate:
          type: integer
          format: int64
        yearlyRate:
          type: integer
          format: int64
          minimum: 1
      required:
        - name

    UpdatePlanResponse:
      type: object
      properties:
        planId:
          type: integer
          format: int64


    GetPlanResponse:
      type: object
      properties:
        plan:
          type: object
          $ref: "#/components/schemas/Plan"

    SearchPlanResponse:
      type: object
      properties:
        plans:
          type: array
          items:
            $ref: "#/components/schemas/Plan"

    Plan:
      type: object
      properties:
        id:
          type: integer
          format: int64
        siteId:
          type: integer
          format: int64
        partnerId:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        active:
          type: boolean
          default: true
        rate:
          type: object
          $ref: "#/components/schemas/PlanRate"
        convertedRate:
          type: object
          $ref: "#/components/schemas/PlanRate"

    PlanRate:
      type: object
      properties:
        id:
          type: integer
          format: int64
        monthly:
          type: integer
          format: int64
        yearly:
          type: integer
          format: int64
        currency:
          type: string
        exchangeRate:
          type: number
          format: double
          nullable: true


    CreateSubscriptionRequest:
      type: object
      properties:
        planId:
          type: integer
          format: int64
          nullable: true
        subscriberId:
          type: integer
          format: int64
          nullable: true
        orderId:
          type: integer
          format: int64
          nullable: true
      required:
        - planId
        - subscriberId
        - orderId

    CreateSubscriptionResponse:
      type: object
      properties:
        subscriptionId:
          type: integer
          format: int64


    SearchSubscriptionResponse:
      type: object
      properties:
        subscriptions:
          type: array
          items:
            $ref: "#/components/schemas/Subscription"

    GetSubscriptionResponse:
      type: object
      properties:
        subscription:
          type: object
          $ref: "#/components/schemas/Subscription"

    Subscription:
      type: object
      properties:
        id:
          type: integer
          format: int64
        siteId:
          type: integer
          format: int64
        planId:
          type: integer
          format: int64
        subscriberId:
          type: integer
          format: int64
        orderId:
          type: integer
          format: int64
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        status:
          type: string
          description: "ACTIVE | CANCELLED | EXPIRED"
        subscriptionDateTime:
          type: string
          format: date-time

    CountSubscriptionResponse:
      type: object
      properties:
        count:
          type: integer
          format: int64

