openapi: "3.0.0"
info:
  title: "Wutsi Twitter API"
  description: |
    API for sharing stories on Twitter.
  version: "1.0.0"

servers:
  - url: https://wutsi-twitter-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-twitter-prod.herokuapp.com
    description: Sandbox

paths:
  /v1/twitter/share:
    get:
      operationId: "share"
      summary: "Share a Story on Twitter"
      parameters:
        - in: query
          name: story-id
          description: ID of the story to share
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
      tags:
        - Twitter
