openapi: "3.0.0"
info:
  title: "Wutsi Twitter API"
  description: |
    API for sharing stories on Twitter.
  version: "1.0.0"

servers:
  - url: https://wutsi-twitter-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-twitter-prod.herokuapp.com
    description: Sandbox

paths:
  /v1/twitter/share:
    get:
      operationId: "share"
      summary: "Share a Story"
      parameters:
        - in: query
          name: story-id
          description: ID of the story to share
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
      tags:
        - Twitter

  /v1/twitter/account/{user-id}:
    post:
      operationId: "save-account"
      summary: "Store Account Information"
      description: |
        Save the information of a Twitter account of a given user
      parameters:
        - in: path
          name: user-id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveAccountRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveAccountResponse'
      tags:
        - Twitter

components:
  schemas:
    SaveAccountRequest:
      type: object
      properties:
        twitterId:
          type: integer
          format: int64
          example: 123
        twitterScreenName:
          type: string
        pictureUrl:
          type: string
          nullable: true
        accessToken:
          type: string
        accessTokenSecret:
          type: string
      required:
        - twitterId
        - twitterScreenName
        - accessToken
        - accessTokenSecret

    SaveAccountRequest:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
          example: 123
