openapi: "3.0.0"
info:
  title: "Wutsi Channel API"
  version: "1.0.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/channels/{id}:
    get:
      operationId: "get"
      summary: "Return a channel"
      parameters:
        - in: path
          name: id
          description: ID of the channel
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetChannelResponse'
      tags:
        - Twitter


components:
  schemas:
    GetChannelResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
