openapi: "3.0.0"
info:
  title: "Wutsi Newsletter API"
  description: |
    API for sharing stories to Newsletter.
  version: "1.0.0"

servers:
  - url: https://wutsi-newsletter-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-newsletter-prod.herokuapp.com
    description: Production

paths:
  /v1/newsletter/share:
    get:
      operationId: "share"
      summary: "Share a Story to a Newsletter"
      parameters:
        - in: query
          name: story-id
          description: ID of the story to share
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
      security:
        - api_key: [ 'newsletter' ]
      tags:
        - Newletter
  /v1/newsletter/digest:
    get:
      operationId: "digest"
      summary: "Send a new digest to all users"
      parameters:
        - in: query
          name: start-date
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: end-date
          required: true
          schema:
            type: string
            format: date
      responses:
        200:
          description: Success
      security:
        - api_key: [ 'newsletter' ]
      tags:
        - Newletter

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
