openapi: "3.0.0"
info:
  title: "Wutsi Newsletter API"
  description: |
    API for sharing stories to Newsletter.
  version: "1.0.0"

servers:
  - url: https://wutsi-newsletter-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-newsletter-prod.herokuapp.com
    description: Sandbox

paths:
  /v1/newsletter/share:
    get:
      operationId: "share"
      summary: "Share a Story to a Newsletter"
      parameters:
        - in: query
          name: story-id
          description: ID of the story to share
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
      tags:
        - Newletter
