openapi: "3.0.0"
info:
  title: "Wutsi Comment API"
  description: This api managing comments on links
  version: "1.0"

servers:
  - url: https://com-wutsi-prod-comment.herokuapp.com
    description: Production server
  - url: https://com-wutsi-int-comment.herokuapp.com
    description: Sandbox server

paths:
  /v1/comments:
    post:
      operationId: "create"
      summary: "Add a comment to a link"
      requestBody:
        description: comment request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateCommentResponse"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
      tags:
        - comment

  /v1/comments/stats:
    get:
      operationId: "stats"
      summary: "Returns the comment statistics of a link"
      parameters:
        - in: path
          name: link
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStatsResponse'
        404:
          description: Link not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
      tags:
        - comment

  /v1/comment/{id}:
    post:
      operationId: "update"
      summary: "Update a comment"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
            format: int64
      responses:
        200:
          description: Success
        404:
          description: Link not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
      tags:
        - comment

    delete:
      operationId: "delete"
      summary: "Delete a comment"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
            format: int64
      responses:
        200:
          description: Success
      security:
        - api_key: []
      tags:
        - comment

components:
  schemas:
    CreateCommentRequest:
      $ref: "models/CreateCommentRequest.yaml"
    CreateCommentResponse:
      $ref: "models/CreateCommentResponse.yaml"
    GetStatsResponse:
      $ref: "models/GetStatsResponse.yaml"
    ErrorResponse:
      $ref: "../../common/v1/ErrorResponse.yaml"

  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-wutsi-api-key
