@startuml
class Link {
  url
}

class Site {
}

class Comment {
  creationDateTime
  updateDateTime
  text
}

class Reader {
  deviceId
  userId
}

Link -> "*" Comment
Link "*" --> Site
Comment "*" -> Reader
@enduml
