openapi: "3.0.0"
info:
  title: "Wutsi Comment API"
  description: This api managing comments on Stories
  version: "1.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/comments:
    get:
      operationId: "search"
      summary: "Search comments"
      parameters:
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            format: int32
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchCommentResponse"
      tags:
        - Comment


components:
  schemas:
    SearchCommentResponse:
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: "#/components/schemas/Comment"

    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        storyId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        text:
          type: string
        creationDateTime:
          type: integer
          format: int64
        modificationDateTime:
          type: integer
          format: int64


