openapi: "3.0.0"
info:
  title: "Wutsi Like API"
  description: This api used for managing likes on Stories
  version: "1.0.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/likes:
    get:
      operationId: "search"
      summary: "Search Likes"
      parameters:
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            format: int32
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchLikeResponse"
      tags:
        - Like

  /v1/likes/{id}:
    get:
      operationId: "get"
      summary: "Get a Like"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int65
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetLikeResponse"
      tags:
        - Like

components:
  schemas:
    SearchLikeResponse:
      type: object
      properties:
        likes:
          type: array
          items:
            $ref: "#/components/schemas/Like"

    GetLikeResponse:
      type: object
      properties:
        like:
          type: object
          $ref: "#/components/schemas/Like"

    Like:
      type: object
      properties:
        id:
          type: integer
          format: int64
        storyId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
          nullable: true
        deviceId:
          type: string
          nullable: true
        likeDateTime:
          type: integer
          format: int64

