openapi: "3.0.0"
info:
  title: "Wutsi Scheduled Post API"
  version: "1.0.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/posts/{id}:
    get:
      operationId: "get"
      summary: "Return a post"
      parameters:
        - in: path
          name: id
          description: ID of the post
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPostResponse'
      tags:
        - Twitter

components:
  schemas:
    GetPostResponse:
      type: object
      properties:
        post:
          type: object
          $ref: '#/components/schemas/Post'

    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 111
        storyId:
          type: integer
          format: int64
          example: 123
        channelType:
          type: string
        status:
          type: string
        message:
          type: string
          nullable: true
        pictureUrl:
          type: string
          nullable: true
        includeLink:
          type: boolean
          nullable: false
          default: true
        language:
          type: string
          nullable: true
        scheduledPostDateTime:
          type: string
          format: date-time
        postDateTime:
          type: string
          format: date-time
        modificationDateTime:
          type: string
          format: date-time
