openapi: "3.0.0"
info:
  title: "Wutsi Email API"
  description: |
    API for sending emails.
  version: "1.0.0"

servers:
  - url: https://wutsi-mail-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-mail-prod.herokuapp.com
    description: Production

paths:
  /v1/emails:
    post:
      operationId: "send"
      summary: "Send and email"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailRequest'
      responses:
        200:
          description: Success
      tags:
        - Email

  /v1/sites/{site-id}/list/members:
    delete:
      operationId: "unsubscribe from site"
      summary: "Unsubscribe an email from a site"
      parameters:
        - in: path
          name: site-id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: email
          description: Email to remove from the list
          required: true
          schema:
            type: string
            format: email
      responses:
        200:
          description: Success
      tags:
        - Mailing List


  /v1/users/{user-id}/list/members:
    delete:
      operationId: "unsubscribe from user"
      summary: "Unsubscribe an email from a user mailing list"
      parameters:
        - in: path
          name: user-id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: email
          description: Email to remove from the list
          required: true
          schema:
            type: string
            format: email
      responses:
        200:
          description: Success
      tags:
        - Mailing List

components:
  schemas:
    SendEmailRequest:
      type: object
      properties:
        siteId:
          type: integer
          format: int64
          example: 1
        sender:
          type: object
          nullable: true
          $ref: '#/components/schemas/Address'
        recipient:
          type: object
          $ref: '#/components/schemas/Address'
        subject:
          type: string
        body:
          type: string
      required:
        - siteId
        - subject
        - recipient

    Address:
      type: object
      properties:
        displayName:
          type: string
          nullable: true
        email:
          type: string
          format: email
      required:
        - email
