openapi: "3.0.0"
info:
  title: "Wutsi Like API"
  description: This api used for managing likes on links
  version: "0.0.2"

servers:
  - url: https://com-wutsi-prod-like.herokuapp.com
    description: Production
  - url: https://com-wutsi-int-like.herokuapp.com
    description: Sandbox

paths:
  /v1/likes:
    get:
      operationId: "search"
      summary: "Search the likes for a given link"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: canonical_url
          required: true
          schema:
            type: string
            nullable: false
        - in: query
          name: user_id
          required: false
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: device_uuid
          required: false
          schema:
            type: string
            nullable: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchLikeResponse'
        404:
          description: Like not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
      tags:
        - Like

    post:
      operationId: "create"
      summary: "Add a Like to a link"
      requestBody:
        description: Like request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLikeRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateLikeResponse"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
      tags:
        - Like

  /v1/likes/stats:
    get:
      operationId: "stats"
      summary: "Returns the Like statistics of a link"
      parameters:
        - in: query
          name: canonical_url
          required: true
          schema:
            type: string
            nullable: false
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStatsResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - api_key: []
      tags:
        - Like

  /v1/likes/{id}:
    delete:
      operationId: "delete"
      summary: "Unlike a link"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
            format: int64
      responses:
        200:
          description: Success
      security:
        - api_key: []
      tags:
        - Like

components:
  schemas:
    CreateLikeRequest:
      type: object
      properties:
        canonicalUrl:
          type: string
          format: uri
          nullable: false
        deviceUUID:
          type: string
          format: uuid
          nullable: true
        userId:
          type: integer
          format: int64
          nullable: true
      required:
        - canonicalUrl

    CreateLikeResponse:
      type: object
      properties:
        likeId:
          type: integer
          format: int64
          nullable: false
          example: 1

    GetStatsResponse:
      type: object
      properties:
        canonicalUrl:
          type: string
          format: uri
          nullable: false
          example: "https://www.foo.com/read/123"
        count:
          type: number
          format: int64
          nullable: false
          example: 1500

    SearchLikeResponse:
      type: object
      properties:
        likes:
          type: array
          items:
            $ref: '#/components/schemas/Like'

    Like:
      type: object
      properties:
        canonicalUrl:
          type: string
          format: uri
          nullable: false
          example: "https://www.foo.com/read/123"
        userId:
          type: integer
          format: int64
          nullable: true
          example: 1
        deviceUUID:
          type: string
          format: uuid
          nullable: true
          example: "8e976869-2b06-407b-95ea-9e69da162a0c"
        likeDateTime:
          type: string
          format: date-time
          nullable: false
          example: "2017-07-21T17:32:28Z"

    ErrorResponse:
      $ref: "../../common/v1/ErrorResponse.yaml"

  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-wutsi-api-key
