@startuml


class LikeBadge << WebComponent >> 
note top of LikeBadge: "Display Like badge on Web"  

class LikeAPI << REST API>>


class Like {
  url
  likeDateTime 
  deviceId
  userId
  siteId
}

LikeAPI -> "*" Like 
LikeBadge --> LikeAPI



@enduml
