openapi: "3.0.0"
info:
  title: "Wutsi User API"
  description: |
    This API manages the Users.
  version: "1.0.0"

servers:
  - url: https://int-com-wutsi-blog.herokuapp.com
    description: Sandbox
  - url: https://com-wutsi-blog.herokuapp.com
    description: Production

paths:
  /v1/users:
    get:
      operationId: "search"
      summary: "Search Users"
      parameters:
        - in: query
          name: blog
          schema:
            type: boolean
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUserResponse'
      tags:
        - User

  /v1/users/{id}/wallet:
    post:
      operationId: "wallet"
      summary: "Save user's wallet information"
      parameters:
        - in: path
          name: id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveWalletRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
      tags:
        - User

  /v1/users/{id}/followers:
    get:
      operationId: "followers"
      summary: "Return followers of a given user"
      parameters:
        - in: path
          name: id
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: follower-user-id
          schema:
            type: integer
            format: int64
            nullable: true
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchFollowerResponse'
      tags:
        - Follower

components:
  schemas:
    GetUserResponse:
      type: object
      properties:
        user:
          type: object
          $ref: "#/components/schemas/User"

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
          default: -1
        siteId:
          type: integer
          format: int64
          example: 123
          default: 1
        name:
          type: string
        email:
          type: string
          nullable: true
        fullName:
          type: string
        pictureUrl:
          type: string
          format: uri
          nullable: true
        language:
          type: string
          nullable: true
        testUser:
          type: boolean
        followerCount:
          type: integer
          format: int64
        subscriberCount:
          type: integer
          format: int64
        wallet:
          type: object
          $ref: "#/components/schemas/Wallet"
          nullable: true


    SearchUserResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: "#/components/schemas/UserSummary"

    UserSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
          default: -1
        siteId:
          type: integer
          format: int64
          example: 123
          default: 1
        name:
          type: string
        email:
          type: string
          nullable: true
        fullName:
          type: string
        pictureUrl:
          type: string
          format: uri
          nullable: true
        language:
          type: string
          nullable: true
        testUser:
          type: boolean
        followerCount:
          type: integer
          format: int64
        subscriberCount:
          type: integer
          format: int64


    SearchFollowerResponse:
      type: object
      properties:
        followers:
          type: array
          items:
            $ref: "#/components/schemas/Follower"

    Follower:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        followerUserId:
          type: integer
          format: int64


    SaveWalletRequest:
      type: object
      properties:
        type:
          type: string
        mobileNumber:
          type: string
        mobileProvider:
          type: string
        country:
          type: string
      required:
        - type
        - mobileNumber
        - mobileProvider
        - country

    SaveWalletResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64

    Wallet:
      type: object
      properties:
        type:
          type: string
        mobileNumber:
          type: string
        mobileProvider:
          type: string
        country:
          type: string
