name: master

on:
  push:
    branches:
      - master

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install
        run: |
          npm install -g @apidevtools/swagger-cli

      - name: build
        run: |
          chmod +x build.sh
          ./build.sh

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws s3 sync \
          --acl public-read \
          --region us-east-1 \
          target/ s3://wutsi-openapi/
