name: pull_request

on: [ pull_request ]

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install-swagger-cli
        run: |
          npm install -g @apidevtools/swagger-cli

      - name: validate
        run: |
          chmod +x build.sh
          ./build.sh
